import fs from "node:fs";
import path from "node:path";
import chalk from "chalk";
import { ConfigError } from "../lib/errors.js";
import { VERSION } from "../version.js";

const WORKFLOW_PATH = ".github/workflows/aeneas-extract.yml";

const workflowTemplate = () => `# Confirm Aeneas extraction succeeds
# Generated by aeneas-cli

name: Aeneas extraction

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  extract:
    name: Check Aeneas Extraction
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git curl opam pkg-config libgmp-dev

      - name: Initialize opam
        run: opam init --disable-sandboxing -y -a

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Install aeneas-cli
        run: npm install -g aeneas-cli@${VERSION}

      - name: Cache OCaml environment
        uses: actions/cache@v5
        with:
          path: ~/.opam
          key: \${{ runner.os }}-opam-v1
          restore-keys: |
            \${{ runner.os }}-opam-

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build artifacts
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: \${{ runner.os }}-cargo-\${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            \${{ runner.os }}-cargo-

      - name: Cache Aeneas repository
        uses: actions/cache@v5
        with:
          path: .aeneas
          key: \${{ runner.os }}-aeneas-\${{ hashFiles('aeneas-config.yml') }}
          restore-keys: |
            \${{ runner.os }}-aeneas-

      - name: Install Aeneas
        run: aeneas-cli install

      - name: Extract to Lean
        run: aeneas-cli extract

      - name: Check for modifications in generated files
        run: |
          if git diff --exit-code; then
            echo "✓ Generated files match committed versions"
          else
            echo "❌ Generated files differ from committed versions"
            echo ""
            echo "Run 'aeneas-cli extract' locally and commit the results."
            exit 1
          fi
`;

export function hasAeneasWorkflow(root: string): boolean {
  const workflowsDir = path.join(root, ".github", "workflows");
  if (!fs.existsSync(workflowsDir)) return false;
  const files = fs.readdirSync(workflowsDir).filter((f) => f.endsWith(".yml") || f.endsWith(".yaml"));
  return files.some((f) => {
    const content = fs.readFileSync(path.join(workflowsDir, f), "utf-8");
    return content.includes("aeneas-cli");
  });
}

export async function ciCommand(root: string): Promise<void> {
  const workflowFile = path.join(root, WORKFLOW_PATH);

  if (fs.existsSync(workflowFile)) {
    throw new ConfigError(`${WORKFLOW_PATH} already exists`, {
      hint: "Delete it first if you want to regenerate",
    });
  }

  fs.mkdirSync(path.dirname(workflowFile), { recursive: true });
  fs.writeFileSync(workflowFile, workflowTemplate(), "utf-8");

  console.log(chalk.green(`  Created ${WORKFLOW_PATH}`));
  console.log(chalk.dim("  This workflow installs Aeneas and runs extraction on every push/PR."));
}
